### ISSUE TITLE
HERMES search function: _cf files

### ISSUE THREAD

**Issue by mike-ivs** [IvS-KULeuven/IvSPythonRepository#12]
The new suffix on hermes files is "_cf". Would be good to expand the search function to account for this / other search options.

**Comment by karandis** [comment]
New keyword added to the search function called 'extension'. This can be set by the user ('c' or 'cf', by default the latter). Note that some of the files are not corrected for flat fields ('_c' exists but no '_cf'). I have tested this and it seems to work fine :) 
Cheers
