### ISSUE TITLE
IvSgui importerror QtGui

### ISSUE THREAD

**Issue by matthiasfabry** [IvS-KULeuven/IvSPythonRepository#17]
When running `ivsgui`
I get an import error:
`Traceback (most recent call last):
  File "/Users/matthiasf/Software/ivs/gui/main.py", line 8, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/Users/matthiasf/anaconda3/envs/ivs/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/Users/matthiasf/anaconda3/envs/ivs/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/Users/matthiasf/anaconda3/envs/ivs/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 13, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/Users/matthiasf/anaconda3/envs/ivs/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding`

I have updated matplotlib and am using the ivs_repo environment.
Cheers
Matthias

**Comment by mike-ivs** [comment]
Hmmm, can you check `conda list` to see if you have 'qt' installed? Then (installed or not) can you paste the output here? 

Cheers,
Mike

**Comment by matthiasfabry** [comment]
No, apparently qt is not installed.
`packages in environment at /Users/matthiasf/anaconda3/envs/ivs:
astropy                   2.0.1               np113py36_0
atomicwrites              1.3.0                    py36_1  
attrs                     19.2.0                     py_0  
blas                      1.0                         mkl  
ca-certificates           2019.8.28                     0  
certifi                   2019.9.11                py36_0  
cycler                    0.10.0           py36hfc81398_0  
ephem                     3.7.6.0          py36h1de35cc_1  
freetype                  2.9.1                hb4e5f40_0  
h5py                      2.8.0            py36h878fce3_3  
hdf5                      1.10.2               hfa1e0ec_1  
icu                       58.2                 h4b95b61_1  
importlib_metadata        0.23                     py36_0  
intel-openmp              2019.4                      233  
kiwisolver                1.1.0            py36h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libxml2                   2.9.9                hf6e021a_1  
libxslt                   1.1.33               h33a18ac_0  
lxml                      3.8.0            py36h1003d81_0  
matplotlib                3.1.1            py36h54f8f79_0  
mkl                       2018.0.3                      1  
more-itertools            7.2.0                    py36_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.13.1           py36h93d791d_2  
openssl                   1.0.2t               h1de35cc_1  
packaging                 19.2                       py_0  
pandas                    0.20.3           py36hd6655d8_2  
pip                       19.2.3                   py36_0  
pluggy                    0.13.0                   py36_0  
py                        1.8.0                    py36_0  
pyparsing                 2.4.2                      py_0  
pytest                    5.2.1                    py36_0  
python                    3.6.2               hd04bb42_19  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.3                     py_0  
readline                  7.0                  h1de35cc_5  
scipy                     0.19.1           py36h3e758e1_3  
setuptools                41.4.0                   py36_0  
six                       1.12.0                   py36_0  
sqlite                    3.30.0               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.3            py36h1de35cc_0  
uncertainties             3.0.2                 py36_1001 
wcwidth                   0.1.7            py36h8c6ec74_0  
wheel                     0.33.6                   py36_0  
xz                        5.2.4                h1de35cc_4  
zipp                      0.6.0                      py_0  
zlib                      1.2.11               h1de35cc_3 `

Is qt supposed to be part of the ivs_repo environment?

**Comment by mike-ivs** [comment]
That makes it (hopefully) an easy fix, i'll explicitly add 'qt' into the environment yml file!

**Comment by mike-ivs** [comment]
Just added it to the .yml file. Could you run `git pull` and then re-install the environment (i.e. `conda env remove --name ivs_repo_3.6`, then `conda env create -f IvS_repo_3.6.yml` using the updated file). 

Let me know if this sorts the issue!

**Comment by matthiasfabry** [comment]
This works!
A clean boot-up of the gui. Thanks!

One small (and harmless) warning though:
`Fontconfig warning: ignoring UTF-8: not a valid region tag`
I'm sure this issue cannot be solved from your end, but I might as well report it

Thanks again
Matthias

**Comment by mike-ivs** [comment]
Brilliant! 

I'm not sure if the FontConfig error can be either, but i'll listen out in case anyone else has that issue too.

Cheers,
Mike
