### ISSUE TITLE
Installation of the conda environment fails on Macos

### ISSUE THREAD

**Issue by WimDeMeester** [IvS-KULeuven/IvSPythonRepository#5]
When I try to install the conda environment for the python repository, I get the following error while executing 

_conda env create -f IvS_repo.yml_

NoPackagesFoundError: Package missing in current osx-64 channels:
  - dbus 1.10.20 0

**Comment by WimDeMeester** [comment]
Extra packages that can not be instaled on a mac:
+ gst-plugins-base 1.8.0 0
+ gstreamer 1.8.0 0
+ libgcc 5.2.0 0
+ libxcb 1.12 1
+ pycairo 1.10.0 py27_0

A possible solution is to create a separate IvS_repo file for both Linux and Macos. When I remove all these packages, the anaconda environment can be created. 

Everything seems to work fine after this, however, I just played a bit around, so I did not really test the python repository. Als the compilation of the fortran code seemed to work.

**Comment by mike-ivs** [comment]
Thanks for the updates about the installation, Nicola encountered the same conda environment problems so we do plan on having both a Linux and Macos IvS_repo.yml file.

**Comment by mike-ivs** [comment]
The conda environment file is now platform independent!
