### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by dbowman234** [IvS-KULeuven/IvSPythonRepository#7]
I get an ImportError on:
from ivs.units.uncertainties.unumpy import log10,log,exp,sqrt

which is being called as part of ivs.spectra.model and ivs.spectra.tools

**Comment by mike-ivs** [comment]
The file containing the offending imports is ivs.units.conversions.py, it has 3 imports that can be replaced (easily i believe) with numpy:

from ivs.units.uncertainties.unumpy import log10,log,exp,sqrt
from ivs.units.uncertainties.unumpy import sin,cos,tan
from ivs.units.uncertainties.unumpy import arcsin,arccos,arctan 

fix to implement:

import numpy as np

log10() -> np.log10()      etc

**Comment by mike-ivs** [comment]
The 'uncertainties' section of the IvS_repo was actually a 3rd-party module that was manually integrated into our repository. The Uncertainties module has now been integrated into the Conda install for the new Py3 version of the repository and, as far as I'm aware, this issue is resolved!
